# Site settings
title: 此间·我们
description: 以梦为马，诗酒趁年华~
keywords: "日记, 生活, 诗歌, 回忆"
url: "https://cijian.us"
baseurl: ""
paginate: 10

source: ./src

permalink: "/:title"
paginate_path: "/page/:num"

excerpt_separator:  '<!-- more -->'

author:
    name: MurphyL
    email: murphyl@outlook.com
    weibo: MurphyLuo
    github: MurphyL
    twitter: MurphyLuo

plugins: [jekyll-paginate]

sass:
    style: compressed

markdown: kramdown

kramdown:
    input:          GFM
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   "lsquo,rsquo,ldquo,rdquo"
    enable_coderay: false

